/*************************** Sophos.com/RapidResponse ***************************\
| DESCRIPTION                                                                    |
| Lists all blocking events generated by the Software Restriction Policy (SRP).  |
|                                                                                |
| REFERENCE                                                                      |
| https://learn.microsoft.com/en-us/windows-server/identity/software-restriction-|
| policies/software-restriction-policies                                         |
| https://www.isssource.com/wp-content/uploads/2012/02/ISSSource-Application_    |
| Whitelisting_Using_SRP.pdf                                                     |
|                                                                                |
| Version: 1.0                                                                   |
| Author: The Rapid Response Team                                                |
| github.com/SophosRapidResponse                                                 |
\********************************************************************************/


SELECT
STRFTIME('%Y-%m-%dT%H:%M:%SZ', MIN(datetime)) AS first_occurrence,
STRFTIME('%Y-%m-%dT%H:%M:%SZ', MAX(datetime)) AS last_occurrence,
COUNT(*) AS instance,
source,
provider_name,
eventid,
CASE
    WHEN eventid = 865 THEN 'SRP - Blocked by default disallow rule'
    WHEN eventid = 866 THEN 'SRP - Blocked by path rule'
    WHEN eventid = 867 THEN 'SRP - Blocked by publisher rule'
    WHEN eventid = 868 THEN 'SRP - Blocked by hash or zone rule'
    WHEN eventid = 882 THEN 'SRP - Blocked, but no UI acknowledgement shown'
    ELSE 'Unknown'
END AS details,
JSON_EXTRACT(data, '$.UserData.AttemptedPath') AS blocked_program,
JSON_EXTRACT(data, '$.UserData.RulePath') AS rule_path,
JSON_EXTRACT(data, '$.UserData.SrpRuleGuid') AS rule_guid,
data AS raw,
'EVTX' AS Data_Source,
'EVTX.16.0' AS Query
FROM sophos_windows_events
WHERE source = 'Application'
    AND provider_name = 'Microsoft-Windows-SoftwareRestrictionPolicies'
    AND eventid IN (865, 866, 867, 868, 882)
GROUP BY source, provider_name, eventid, blocked_program, rule_path, rule_guid
ORDER BY first_occurrence DESC;
